### ISSUE TITLE
[MySQL] Unsigned datatypes, Double precision cannot be migrated

### ISSUE THREAD

**Issue by chetank-yb** [yugabyte/yb-voyager#188]

**Comment by chetank-yb** [comment]
data which could not be migrated successfully
1. **Double precision** - COPY "floating_point_types" FROM file "/home/ubuntu/export-dir/metainfo/data/floating_point_types.0.5.5.439.P": ERROR: "-1.79769313486232e+308" is out of range for type double precision (SQLSTATE 22003)

**Comment by rahulb-yb** [comment]
1. Float-based data types are always approximations of the values they represent- any values exported near MAX or MIN values may be out of range due to this nature of the datatype.
2. Unsigned datatypes are not native to YB, they are usually enforced by check constraints if the user so wishes to include them. 

Any other suggested solutions may be explored as per the manual review doc: https://docs.google.com/document/d/1ZzPGdn2tSHdbqzQ4b-WdXFRedLaiQqun5osV1vAG-CY
