### ISSUE TITLE
Row mismatch in 'export-dir status' and 'count(*)' after interruptions

### ISSUE THREAD

**Issue by shubham-yb** [yugabyte/yb-voyager#328]
Sometimes after we interrupt `import-data` in between, the command `yb-voyager import data --export-dir ${EXPORT_DIR} status` on the source and the `COUNT(*) for the rows` on the target show different values. 

Mostly it shows more on the target. 

Attaching an example:

Source:

![Image](https://user-images.githubusercontent.com/65844208/190596528-53da2a0e-3999-40bc-8341-313344fff785.png)

Target:

![Image](https://user-images.githubusercontent.com/65844208/190596613-1937742c-054c-46c3-8948-a7e1ec82f881.png)

**Comment by amit-yb** [comment]
@shubham-yb, this is an expected behaviour. Consider a case where:
- yb-voyager submits a COPY command (with 100K records)
- the command completes successfully on the server
- yb-voyager is interrupted before it could update its local state to mark the batch as DONE 

The `import data status` command looks at the local persistent state to count the imported row count. That's why, _Mostly it shows more on the target._

Once the import is done, the counts reported by `COUNT(*)` and `import data status` must match.
